### ISSUE TITLE
classify.py feature export, create outdir

### ISSUE THREAD

**Issue by dahhei** [KumarLabJax/JABS-behavior-classifier#33]
When running classify.py with feature export in branch, have it create a folder if outdir folder does not already exist [classify-save-features](https://github.com/KumarLabJax/JABS-behavior-classifier/tree/classify-save-features)

**Comment by SkepticRaven** [comment]
The branch above was integrated into some larger effort in a newer branch: https://github.com/KumarLabJax/JABS-behavior-classifier/tree/update-prediction-format

Once the now linked update-prediction-format branch is merged, we should close https://github.com/KumarLabJax/JABS-behavior-classifier/tree/classify-save-features in favor of that, since that branch is around 150 commits behind other changes.
